export const CREATE_VITAL = 'CREATE_VITAL';
export const SET_TODAY_VITALS = 'SET_TODAY_VITALS';
export const SET_YESTERDAY_VITALS = 'SET_YESTERDAY_VITALS';
export const SET_MORE_THAN_1_DAY_AGO_VITALS = 'SET_MORE_THAN_1_DAY_AGO_VITALS';
export const CREATE_USER = 'CREATE_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
