export const CREATE_VITAL = 'CREATE_VITAL';
export const SET_TODAY_VITALS = 'SET_TODAY_VITALS';
export const SET_YESTERDAY_VITALS = 'SET_YESTERDAY_VITALS';
export const SET_LAST_WEEK_VITALS = 'SET_LAST_WEEK_VITALS';
export const CREATE_USER = 'CREATE_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
